#!/usr/bin/env ruby -w
# encoding: UTF-8

module Kryptos
  # These are the four parts of the Kryptos sculpture
  # (http://en.wikipedia.org/wiki/Kryptos) as well as
  # an example of a Vigenère cipher table.

  PART_ONE = 'EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJYQTQUXQ'\
  'BQVYUVLLTREVJYQTMKYRDMFD'

  # I've added an extra 'S' eight characters before the
  # end of PART_TWO in order to correct Jim's error (the
  # final words should be "X LAYER TWO" not "ID BY ROWS").
  PART_TWO = 'VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?D'\
  'QMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEU'\
  'NAQZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJH'\
  'KFWHKUWQLSZFTIHHDDDUVH?DWKBFUFPWNTDFIYCUQZEREEVLDKF'\
  'EZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ?FKZBSFDQVGOGIPUFX'\
  'HHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEE'\
  'XBDMVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUM'\
  'EBEDMHDAFMJGZNUPLGESWJLLAETG'

  PART_THREE = 'ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNR'\
  'EYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLPI'\
  'IACAEWMTWNDITEENRAHCTENEUDRETNHAEOETFOLSEDTIWENHAEI'\
  'OYTEYQHEENCTAYCREIFTBRSPAMHHEWENATAMATEGYEERLBTEEFO'\
  'ASFIOTUETUAEOTOARMAEERTNRTIBSEDDNIAAHTTMSTEWPIEROAG'\
  'RIEWFEBAECTDDHILCEIHSITEGOEAOSDDRYDLORITRKLMLEHAGTD'\
  'HARDPNEOHMGFMFEUHEECDMRIPFEIMEHNLSSTTRTVDOHW?'

  PART_FOUR = 'OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWT'\
  'QSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUH'\
  'UAUEKCAR'

  EXAMPLE_VIGENERE_TABLE = [
    %w[K R Y P T O S A B C D E F G H I J L M N Q U V W X Z],
    %w[P T O S A B C D E F G H I J L M N Q U V W X Z K R Y],
    %w[A B C D E F G H I J L M N Q U V W X Z K R Y P T O S],
    %w[L M N Q U V W X Z K R Y P T O S A B C D E F G H I J],
    %w[I J L M N Q U V W X Z K R Y P T O S A B C D E F G H],
    %w[M N Q U V W X Z K R Y P T O S A B C D E F G H I J L],
    %w[P T O S A B C D E F G H I J L M N Q U V W X Z K R Y],
    %w[S A B C D E F G H I J L M N Q U V W X Z K R Y P T O],
    %w[E F G H I J L M N Q U V W X Z K R Y P T O S A B C D],
    %w[S A B C D E F G H I J L M N Q U V W X Z K R Y P T O],
    %w[T O S A B C D E F G H I J L M N Q U V W X Z K R Y P]
  ]

  EXAMPLE_PLAYFAIR_TABLE = [
    %w[K R Y P T],
    %w[O S A B C],
    %w[D E F G H],
    %w[I J L M N],
    %w[U V W X Z]
  ]
end

