# encoding: UTF-8

require 'rspec/core/rake_task'

ENV['RACK_ENV'] ||= 'development'

task :default => :spec

desc 'Run tests'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = ['--color --format d']
  t.pattern    = './spec/**/*_spec.rb'
end
